sudo: required
dist: trusty

language: scala

notifications:
  on_success: change
  on_failure: change

before_install:
  - sudo apt-add-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update -qq
  - sudo apt-get install bitcoind -y

apt_packages:
  - bitcoind

script: "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"
