language: scala
scala: 
  - 2.11.7

notifications:
  on_success: change
  on_failure: change

before_install:
  - sudo apt-add-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update -qq
  - sudo apt-get install bitcoind -y

apt_packages:
  - bitcoind

before_script:
  - mkdir -p /home/travis/.bitcoin && cp bitcoin.conf /home/travis/.bitcoin/bitcoin.conf
  - dpkg -L bitcoind 
  - /usr/bin/bitcoind -regtest -daemon

script: "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"
